const Event = {
    CONNECT:'CONNECT',
    DISCONNECT:'DISCONNECT',
    REQUEST:'REQUEST',
    READY:'READY',
    HIGH_LOW:'HIGH_LOW',
    UPDATE_DATA:'UPDATE_DATA',
    UPDATE_ALL:'UPDATE_ALL',
    PURCHASE_CONTRACT:'PURCHASE_CONTRACT',
    TRANSCATION_COMPLETE:'TRANSCATION_COMPLETE',
    SESSION_COMPLETE:'SESSION_COMPLETE',
    SAVE_DATA_TO_FILE:'SAVE_DATA_TO_FILE'
}
module.exports = Event;