const Event = {
    CONNECT:'CONNECT',
    DISCONNECT:'DISCONNECT',
    REQUEST:'REQUEST',
    READY:'READY',
    HIGH_LOW:'HIGH_LOW',
    UPDATE_DATA:'UPDATE_DATA',
    UPDATE_ALL:'UPDATE_ALL',
    PURCHASE_CONTRACT:'PURCHASE_CONTRACT',
    TRANSCATION_COMPLETE:'TRANSCATION_COMPLETE'
}
module.exports = Event;